version: "3.8"

services:
  bff:
    build: ./bff
    ports:
      - "4567:4567"
    command: bash -c "bundle install && bundle exec puma -p 4567"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
