# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
gem 'httparty', '~> 0.22.0'
gem 'rack', '~> 3.1', '>= 3.1.4'
gem 'rack-test', '~> 2.1.0'
gem 'sinatra', '~> 4.0.0'
gem 'json', '~> 2.7', '>= 2.7.2'
gem 'rspec', '~> 3.13.0'
gem 'dotenv', '~> 3.1', '>= 3.1.2'
gem 'puma', '~> 6.4', '>= 6.4.2'
gem 'redis', '~> 4.8.0'
gem 'fakeredis', '~> 0.9.0'
